import type { ProductDefinition } from "./types.ts";

export const PRODUCT_CATALOG: readonly ProductDefinition[] = [
  {
    productId: "PROD-HOM-001",
    productName: "Linen Throw Set",
    category: "Home",
    unitPriceCents: 8_800,
    unitCostCents: 4_200,
    baseWeight: 22,
  },
  {
    productId: "PROD-HOM-002",
    productName: "Stoneware Serving Bowl",
    category: "Home",
    unitPriceCents: 6_200,
    unitCostCents: 3_100,
    baseWeight: 2.5,
  },
  {
    productId: "PROD-HOM-003",
    productName: "Everyday Candle Trio",
    category: "Home",
    unitPriceCents: 3_600,
    unitCostCents: 1_400,
    baseWeight: 3,
  },
  {
    productId: "PROD-KIT-001",
    productName: "Essential Cookware Set",
    category: "Kitchen",
    unitPriceCents: 22_000,
    unitCostCents: 19_700,
    baseWeight: 5,
  },
  {
    productId: "PROD-KIT-002",
    productName: "Glass Meal Prep Set",
    category: "Kitchen",
    unitPriceCents: 5_800,
    unitCostCents: 2_700,
    baseWeight: 3,
  },
  {
    productId: "PROD-KIT-003",
    productName: "Acacia Cutting Board",
    category: "Kitchen",
    unitPriceCents: 5_400,
    unitCostCents: 2_500,
    baseWeight: 2.5,
  },
  {
    productId: "PROD-WEL-001",
    productName: "Recovery Massage Kit",
    category: "Wellness",
    unitPriceCents: 11_800,
    unitCostCents: 5_800,
    baseWeight: 2.5,
  },
  {
    productId: "PROD-WEL-002",
    productName: "Botanical Bath Set",
    category: "Wellness",
    unitPriceCents: 6_400,
    unitCostCents: 2_800,
    baseWeight: 2,
  },
  {
    productId: "PROD-WEL-003",
    productName: "Yoga Support Bundle",
    category: "Wellness",
    unitPriceCents: 9_200,
    unitCostCents: 4_200,
    baseWeight: 2,
  },
  {
    productId: "PROD-WOR-001",
    productName: "Focus Desk Lamp",
    category: "Workspace",
    unitPriceCents: 9_600,
    unitCostCents: 4_200,
    baseWeight: 2.5,
  },
  {
    productId: "PROD-WOR-002",
    productName: "Felt Desk Organizer",
    category: "Workspace",
    unitPriceCents: 4_800,
    unitCostCents: 2_000,
    baseWeight: 2,
  },
  {
    productId: "PROD-WOR-003",
    productName: "Ergonomic Laptop Stand",
    category: "Workspace",
    unitPriceCents: 8_200,
    unitCostCents: 3_800,
    baseWeight: 2,
  },
  {
    productId: "PROD-OUT-001",
    productName: "Trail Hydration Pack",
    category: "Outdoor",
    unitPriceCents: 7_400,
    unitCostCents: 3_400,
    baseWeight: 2.5,
  },
  {
    productId: "PROD-OUT-002",
    productName: "Weatherproof Picnic Blanket",
    category: "Outdoor",
    unitPriceCents: 6_800,
    unitCostCents: 3_000,
    baseWeight: 2,
  },
  {
    productId: "PROD-OUT-003",
    productName: "Enamel Camp Mug Set",
    category: "Outdoor",
    unitPriceCents: 4_400,
    unitCostCents: 3_500,
    baseWeight: 2,
  },
  {
    productId: "PROD-GFT-001",
    productName: "Discovery Gift Bundle",
    category: "Gifting",
    unitPriceCents: 4_800,
    unitCostCents: 4_500,
    baseWeight: 0.6,
    availableFrom: "2024-03-01",
    availableTo: "2025-03-31",
  },
  {
    productId: "PROD-GFT-002",
    productName: "Seasonal Host Gift Box",
    category: "Gifting",
    unitPriceCents: 7_800,
    unitCostCents: 3_600,
    baseWeight: 3,
    availableFrom: "2024-10-01",
  },
] as const;

export const CATEGORIES = [...new Set(PRODUCT_CATALOG.map((product) => product.category))].sort();
